### ISSUE TITLE
Change order

### ISSUE THREAD

**Issue by LeonNicholls** [LeonNicholls/Open-Launcher-for-GTV#4]
The only thing I can think of that would be useful is the ability to reorganize the order of the items in a row and to reorganize the order of the rows themselves.

**Comment by ghost** [comment]
Just installed the app and I really love it :-)! I did quickly notice the lack of ability to do re-ordering and did feel the lack of both of these capabilities (reorder items and reorder rows). Look forward to a future release with these functions :-)!

**Comment by LeonNicholls** [comment]
1.3 support re-ordering items

**Comment by ghost** [comment]
Just tested. Re-ordering is not working for me as I have multiple rows. When I select an item on the top row (named "Google TV") and select it to move, when I push an arrow key it pops to the second row ("Favorites"). It also then seems to be confused and shows the wrong icon labels (from the wrong row) and the wrong row names.

**Comment by LeonNicholls** [comment]
saeba79 I'm not able to reproduce the issue you are reporting. Contact me at openlauncher@entertailion.com so that I can debug the issue with you.

**Comment by ghost** [comment]
OK. Sent email with steps to reproduce. 

What we uncovered: I was long-clicking on the item to bring up the menu to select "Move Item". This evidently caused an issue. Using the menu key to bring up the menu instead works flawlessly. 

Thanks!

**Comment by LeonNicholls** [comment]
1.4 supports changing the order of the rows.
