### ISSUE TITLE
Ability to edit/rename favorite channels

### ISSUE THREAD

**Issue by ghost** [LeonNicholls/Open-Launcher-for-GTV#9]
Some of my favorite channels were added with generic icons and station names like WKCF. I'd like to be able to edit/rename these to be more identifiable (CW, CBS, etc.).

**Comment by LeonNicholls** [comment]
1.3 supports automatic TV network name mapping for USA

**Comment by ghost** [comment]
This was a big improvement... but there were still some channels that could use renaming (BH GIORL TBSHD, BH GIORL ESPN ESPNHD).

**Comment by LeonNicholls** [comment]
1.4 allows you to change the TV channel name before it is added to a row in the launcher.
